round:
  speed: 15
  cooldown: 50
homingMissile:
  speed: 25  
  angleSpeedDeg: 7.5
  maxOnScreen: 5
  cooldown: 500
  lifespan: 45
  fallSpeed: 
    x: 0.5
    y: 2
    rotation: 5
parachute:
  xSpeed: 3
  ySpeed: 1
  chance: 20

gameStages:
  - scoreToBeat: 20
    plateConfig:
      - type: speed1
        count: 4
  # - scoreToBeat: 5
  #   plateConfig:
  #     - type: speed1
  #       count: 2
  - scoreToBeat: 20
    plateConfig:
      - type: speed2
        count: 4
  - scoreToBeat: 20
    plateConfig:
      - type: speed2
        count: 3
      - type: speed1
        count: 2
  - scoreToBeat: 20
    plateConfig:
      - type: speed3
        count: 1
  - scoreToBeat: -1
    plateConfig:
      - type: speed4
        count: 1
      - type: speed1
        count: 1
      - type: speed2
        count: 1

plateTypes:
  speed1:
    speed: 3
    horizontalSpeed: 7
    sprite: ./speed1.png
  speed2:
    speed: 6
    horizontalSpeed: 3
    sprite: ./speed2.png
  speed3:
    speed: 8
    horizontalSpeed: 2
    sprite: ./speed3.png
  speed4:
    speed: 12
    horizontalSpeed: 1
    sprite: ./speed4.png

